/// Flutter icons GymIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GymIcons
///      fonts:
///       - asset: fonts/GymIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GymIcons {
  GymIcons._();

  static const _kFontFam = 'GymIcons';
  static const String? _kFontPkg = null;

  static const IconData machine = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardio = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barebell = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
